Location Service
nmondal/cowj pull request #39
Opened 2023-07-22 14:40 UTC by hadric

Added a Location Service in the samples section.

added a readme file - https://github.com/hadric/cowj/blob/main/README.md

2023-07-23 14:10 UTC, nmondal commented on app/samples/LocatorSerivce/distance.js
> +function getDataFromSql(person, jdbc, redis) {
Not required. There is literally a select() in the JDBCWrapper.
It is also being used in tests.

2023-07-23 14:11 UTC, nmondal commented on app/samples/LocatorSerivce/locations.js
> +Test.expect(false, 'User not found', 404 )
The idea of expect was to avoid if/else.
Also that is why Test.panic() exists.

2023-07-23 14:12 UTC, nmondal requested changes
Check the comments!

2023-07-29 15:11 UTC, hadric commented on app/samples/LocatorSerivce/distance.js
> +function getDataFromSql(person, jdbc, redis) {
Yes, i checked the tests, it works for Derby.
when i use mysql and try jdbc.select(findPerson), i am getting below error
InternalError: Can't find method cowj.plugins.JDBCWrapper.select(org.mozilla.javascript.ConsString). (eval#15)

2023-07-29 15:16 UTC, hadric commented on app/samples/LocatorSerivce/locations.js
> +Test.expect(false, 'User not found', 404 )
made the changes .Please check now

2023-07-29 15:19 UTC, hadric commented on app/samples/LocatorSerivce/distance.js
> +function getDataFromSql(person, jdbc, redis) {
again looks like an issue with mozilla rhino

2023-07-29 17:39 UTC, hadric commented on app/samples/LocatorSerivce/distance.js
> +function getDataFromSql(person, jdbc, redis) {
made the changes. Please check.
i was not passing all the params in the select method .

2023-09-13 14:33 UTC, nmondal commented
This was a cool one, great effort. Some interesting bugs were found.
No need to add this to the repo, should be here for historical reason.

2023-09-13 14:33 UTC, closed without merging